# TravisCI (https://travis-ci.org) configuration file
# https://docs.travis-ci.com/user/languages/python

language: python

# ensures that we have UUID filesystem mounts for proper testing
sudo: true

python:
  - "3.4"
#  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y sshfs
  # add travis user to fuse group
  - sudo gpasswd -a travis fuse
  - sudo groupadd newtravisgroup
  - groups
  - whoami

install:
  - pip install coveralls
  - groups
  - groups travis
  - getent group
  - cat /etc/group
  - touch newfile
  - whoami
  - ls -al
  - sudo usermod -a -G fuse,newtravisgroup $USER
  - chgrp fuse newfile | echo "0"
  - chgrp newtravisgroup newfile | echo "0"

script:
  # compile all files - ensure that syntax is correct
  - touch newfile2
  - sudo -E su $USER -c 'chgrp travis newfile2 | echo 0'
  - sudo -E su $USER -c 'python -m compileall common common/test common/plugins qt4 qt4/plugins'
  # run unit tests - ensure that functionality is correct
  - cd common && ./configure && make unittest-v

after_success:
  - coverage combine
  - coveralls
